apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-publish-notready
spec:
  selector:
    matchLabels:
      app: publish-notready
  serviceName: sample-publish-notready
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: publish-notready
    spec:
      containers:
        - name: nginx-container
          image: amsy810/echo-nginx:v2.0
          readinessProbe:
            exec:
              command: ["sh", "-c", 'exit 1']
---
apiVersion: v1
kind: Service
metadata:
  name: sample-publish-notready
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - port: 8080
      targetPort: 80
      name: http-port
      protocol: TCP
  selector:
    app: publish-notready