apiVersion: v1
kind: Pod
metadata:
  name: sample-readinessgate
  labels:
    app: sample-readinessgate
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
  readinessGates:
    - conditionType: "amsy.dev/sample-condition"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-readinessgate
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http-port
  selector:
    app: sample-readinessgate