apiVersion: v1
kind: Pod
metadata:
  name: smaple-emptydir-memory-with-memory-limits
spec:
  containers:
    - name: nginx-container
      image: nginx:1.16
      resources:
        limits:
          memory: 64Mi
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir:
        medium: Memory
        sizeLimit: 128Mi